### ISSUE TITLE
Add language file to rewrite the labels

### ISSUE THREAD

**Issue by PeterDeHaberkorn** [wholecms/core#1]

**Comment by AlejoJamC** [comment]
+1

**Comment by olipiskandar** [comment]
+1

**Comment by BrandonSurowiec** [comment]
+1

**Comment by furkancelik** [comment]
It is okay. I started to work.

**Comment by furkancelik** [comment]
admin panel will bring support for English. multi-language interface system for later

**Comment by furkancelik** [comment]
Translated from Turkish to English.
https://github.com/wholecms/core/tree/1.1.0
