### ISSUE TITLE
Route [master_page] not defined

### ISSUE THREAD

**Issue by MehdiAroui** [wholecms/core#2]
Hey,There is an error when I try to access to the admin page.

Route [master_page] not defined. (View: C:\xampp\htdocs\CMS2\resources\views\vendor\backend\widgets\quick_menu.blade.php) (View: C:\xampp\htdocs\CMS2\resources\views\vendor\backend\widgets\quick_menu.blade.php)

**Comment by furkancelik** [comment]
you should see an error like this.
make sure you are running migrations and seeders.
now by doing the installation I tested it, it works.
