### ISSUE TITLE
[IDEA] Laravel Spark like installer

### ISSUE THREAD

**Issue by russweas** [wholecms/core#3]
I would love to implement this but I'm really busy right now but I still want to get my idea out there. :/.

From first view this package doesn't look very different from laravel/spark at all, structure wise. The way that we can run `spark install` is because of laravel/spark-installer. It shouldn't be that hard to fork laravel/spark-installer, modify it, and save it to wholecms/instaler.

What do you guys think?

**Comment by furkancelik** [comment]
I prepare a package.
the other components to be included in the package.
I don't think now spark installer.
