### ISSUE TITLE
Upload Template Not Working

### ISSUE THREAD

**Issue by olipiskandar** [wholecms/core#4]
After i followed your video tutorial "Create template", i got some error when upload template..
"The Template File Field Cannot Be Left Blank"

**Comment by furkancelik** [comment]
Which template does not work?
You are creating a new template?

**Comment by olipiskandar** [comment]
Yes...i create new template from your video
template_flat

**Comment by furkancelik** [comment]
you send the theme you do?

**Comment by olipiskandar** [comment]
Check your mail sir...
sorry..

**Comment by furkancelik** [comment]
Ok.
I'm testing.

**Comment by furkancelik** [comment]
theme successfully added.
There seems to be an error on the master page

**Comment by olipiskandar** [comment]
what changes ?

**Comment by furkancelik** [comment]
Due to carelessness, a small error.
error solved
https://github.com/wholecms/core/commit/53d8e96cb5881ca1120acceae9756f6829dc6e20
Thank you for reporting.

**Comment by olipiskandar** [comment]
hai @furkancelik , still not work..
![capture](https://cloud.githubusercontent.com/assets/4706142/10245703/449af7d6-6934-11e5-94f7-b8d9831606c3.PNG)

**Comment by furkancelik** [comment]
There is no problem on this page.
Try to re-install the operating (version 1.1.0)
I set up a template that you send from this page.

**Comment by olipiskandar** [comment]
i'm sorry...my bad...
thanks..

**Comment by akhterarif** [comment]
When I'm trying to upload your template_cat.zip in a fresh installed wholeCMS,  this error is showing:-
**FatalErrorException in ComponentsController.php line 75:
Whole\Core\Http\Controllers\Admin\ComponentsController::store(): Failed opening required 'D:\xampp\htdocs\projects\blog\components/Component.php' (include_path='.;D:\xampp\php\PEAR')**
plz answer quickly....
_Thanks in advance_

**Comment by furkancelik** [comment]
Hello, I have not encountered this error before..
Can I see patients by making connections.
